[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
serde_json = "1.0.120"
serde = { version = "1.0.204", features = ["derive"] }
